version: '3.8'

services:
  app:
    image: cordell_stores:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
