version: '3.8'

services:
  app:
    image: cordell_stores:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
    volumes:
      - app_cache:/cache
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  app_cache:
  redis_data: